### ISSUE TITLE
React 16 problem with ref on stateless component

### ISSUE THREAD

**Issue by pocketjoso** [jfschwarz/substyle#19]
Hi there, using this plugin via [react-mentions](https://github.com/effektif/react-mentions).

Just tried upgrading to [React 16](https://github.com/facebook/react/issues/10294), and while it's still in beta, I think these warnings/errors will remain:

![screen shot 2017-08-16 at 18 48 00](https://user-images.githubusercontent.com/7192832/29374992-b6f2995c-82b3-11e7-8142-849cb2925b46.png)

Any chance we can get a fix in and a new version? I've just been adding `div` containers around my functional components where I want to use refs.

**Comment by pocketjoso** [comment]
@jfschwarz friendly ping - would be super awesome to get an update for this. Let me know if you prefer a PR.

**Comment by jfschwarz** [comment]
Thank you for reporting this. I'm having trouble reproducing this warning and would like to kindly ask you for your assistance.

My understanding is that the error message is emitted because of the `ref` passed here: https://github.com/jfschwarz/substyle/blob/master/packages/substyle/src/defaultStyle.js#L41

I tried to reproduce this by upgrading to React@16.0.0-beta.5 and running the test suite. There is one test that specifically tests the ref when using the `defaultStyle` HOC on stateless function components: https://github.com/jfschwarz/substyle/blob/master/packages/substyle/test/defaultStyle.spec.js#L168 However, for me this test does not emit the warning you posted.

Which beta version of React are you using. Could it be that the warning disappeared again in beta.5?

**Comment by jfschwarz** [comment]
I pushed a branch with a check for stateless function components: https://github.com/jfschwarz/substyle/pull/21

I think, there's nothing speaking against having this as a safeguard before setting a ref. Would this fix the warning for you?

**Comment by pocketjoso** [comment]
I tested with `React@16.0.0-beta.5`, the bug is still there.

#21 fixes it though. 👍

**Comment by jfschwarz** [comment]
I've merged #21 and published v6.1.1
